/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "lamport_constants.h"



const lamportConstants g_lamport_constants;

lamportConstants::lamportConstants() {
}



