/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef lamport_CONSTANTS_H
#define lamport_CONSTANTS_H

#include "lamport_types.h"



class lamportConstants {
 public:
  lamportConstants();

};

extern const lamportConstants g_lamport_constants;



#endif
